volumes:
  state:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.3.0/24
          ip_range: 10.1.3.0/28
  cluster:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.inhibit_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 10.1.5.0/24
          ip_range: 10.1.5.0/28

services:
  openwrt:
    build:
      context: .
      dockerfile: Containerfile
      args:
        OPENWRT_VERSION: 23.05.3
    networks:
    - default
    - cluster
    environment:
      OPENWRT_DEBUG: "${OPENWRT_DEBUG}"
      DEFAULT_GATEWAY: 10.1.3.1
    ports:
      - 8080:80
      - 8443:443
      - 8222:22
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun
    - /dev/kvm
    init: true
    stdin_open: true
    tty: true
    volumes:
      - state:/state
    healthcheck:
      test: ["CMD", "curl", "-Ssf", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  dnsmasq:
    build:
      context: dnsmasq/
      dockerfile: Containerfile
    networks:
    - default
    cap_add:
    - NET_ADMIN
    init: true

  node0:
    image: docker.io/alpine:latest
    init: true
    cap_add:
    - NET_ADMIN
    networks:
    - cluster
    command:
    - sleep
    - inf
  node1:
    image: docker.io/alpine:latest
    init: true
    cap_add:
    - NET_ADMIN
    networks:
    - cluster
    command:
    - sleep
    - inf
