volumes:
  state:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.1.3.0/24
  lan0:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.inhibit_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 10.1.5.0/24
  lan1:
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.inhibit_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 10.1.7.0/24

services:
  openwrt:
    build:
      context: .
      dockerfile: Containerfile
      args:
        OPENWRT_VERSION: 23.05.3
    networks:
    - default
    - lan0
    - lan1
    environment:
      OPENWRT_DEBUG: "${OPENWRT_DEBUG}"
      DEFAULT_GATEWAY: 10.1.3.1
    ports:
      - 8080:80
      - 8443:443
      - 8222:22
    cap_add:
    - NET_ADMIN
    devices:
    - /dev/net/tun
    - /dev/kvm
    init: true
    stdin_open: true
    tty: true
    volumes:
      - state:/state
    healthcheck:
      test: ["CMD", "curl", "-Ssf", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  dnsmasq:
    build:
      context: dnsmasq/
      dockerfile: Containerfile
    networks:
    - default
    cap_add:
    - NET_ADMIN
    init: true

  node0:
    build:
      context: node
      dockerfile: Containerfile
    init: true
    cap_add:
    - NET_ADMIN
    networks:
    - lan0
    environment:
      DEFAULT_GATEWAY: 10.1.5.1
  node1:
    build:
      context: node
      dockerfile: Containerfile
    init: true
    cap_add:
    - NET_ADMIN
    networks:
    - lan1
    environment:
      DEFAULT_GATEWAY: 10.1.7.1
